trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'azure-terraform-sc'

stages:

- stage: Deploy
  displayName: Deploy Infrastructure

  jobs:

  - job: DeployAzureResources
    displayName: Create RG and Storage Account

    steps:

    - checkout: self

    - task: AzureCLI@2
      displayName: Execute Deployment Script

      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: scriptPath
        scriptPath: scripts/deploy.sh